### ISSUE TITLE
`prerender: true` doesn't do anything in `+config.h.ts`

### ISSUE THREAD

**Issue by andriygm** [vikejs/vike-solid#58]
Right now, enabling pre-rendering has to be done in the vike-solid config in `vite.config.ts` -- is this intended behavior? if so, it should be documented.

```
solid({
  vps: {
    prerender: true,
  },
}),
```

**Comment by magne4000** [comment]
The Vike documentation states that:

> By default, pre-rendering is disabled. To enable it:


```ts
// vite.config.js

import vike from 'vike/plugin'

export default {
  plugins: [
    vike({
      // Use default settings:
      prerender: true,
      // Or set settings:
      prerender: {
        partial: false,
        noExtraDir: false,
        parallel: 4,
        disableAutoRun: false
      }
    })
  ]
}
```

So indeed it needs to first be enabled through vite config. What's not obvious is how it applies to `vike-solid`, and is related to the fact that `vike-solid/vite` also includes `vike/plugin`, which is not obvious in the documentation.

In order to be on par with other `vike-*` packages, I'll remove `vike/plugin` from `vike-solid/vite`, and also remove the dedicated `vike-solid` CLI

**Comment by magne4000** [comment]
`0.4.0` released, here are the migration steps https://github.com/vikejs/vike-solid/blob/main/MIGRATION.md.
It should now be in concordance with Vike documentation.
